appName: frontend
replicaCount: 2

container:
  image:
    repository: "nguyentankdb17/microserviceapp_frontend"
    tag: "3f9af0f5"
  port: 80
  imagePullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 31000