appName: frontend
replicaCount: 2

container:
  image:
    repository: "nguyentankdb17/microserviceapp_frontend"
    tag: "nguyentankdb17/microservice_app_frontend:49a400ab"
  port: 80
  imagePullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 31000