appName: frontend
replicaCount: 2

container:
  image:
    repository: "nguyentankdb17/microserviceapp_frontend"
    tag: "6d2fc09a"
  port: 80
  imagePullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 31000
