appName: frontend
replicaCount: 1

container:
  image:
    repository: "nguyentankdb17/microserviceapp_frontend"
    tag: "1.0.6"
  port: 80
  imagePullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 31000
